### ISSUE TITLE
The current release of polkabot is lacking critical features in discord

### ISSUE THREAD

**Issue by Nobukand** [okbuddyhololive/polkabot#35]
The release of polkabot lacks the key component that differentiate itself to other discord bot which is the lack of urine. with this missing from the core features, the cord must have a suisei bot or else there will be a immediate degradation of the channel. without the piss, even one of the old members of okbh unfortunately leaved the server such as "brook". god i miss him uoooogh

**Comment by bemxio** [comment]
how would polkabot piss work? lol
