### ISSUE TITLE
message content intent problems

### ISSUE THREAD

**Issue by deemfox** [okbuddyhololive/polkabot#37]
theres no mention of the bot needing the Message Content Intent enabled under Privileged Gateway Intents but it doesnt seem to work at all without it. disabling all privileged gateway intents gives an error but enabling only the server members intent makes it go away and the bot just silently does nothing. 
enabling the message content intent makes it work as expected but it took a few print() statements and some googling for me to get there

if this intent is required i would suggest making note of that in the installation instructions since py-cord pre-2.0 did not have support for intents.message_content. that could be very helpful for people who are new to running discord bots

**Comment by bemxio** [comment]
ah, for some reason i entirely forgot about mentioning the bot's required intents
thank you for making the issue, will work on it ASAP!
