### ISSUE TITLE
Fail on pol count hi 

### ISSUE THREAD

**Issue by KiCMiHABT** [okbuddyhololive/polkabot#39]
I tried to pol count hi multiple times and all of them polkabot failed midway without any answer!!!!!! So mean I think...

**Comment by bemxio** [comment]
will be fixed with the next update :3

**Comment by bemxio** [comment]
it seems like the issue still appears there, weirdly enough it didn't in the beta so thats weird
gonna investigate it while adding an another fix to `pol count`

**Comment by bemxio** [comment]
i have no fucking idea why its appearing, it must be an issue on the database's end but i dont have any clues

**Comment by bemxio** [comment]
it seems like its just taking a really really long time to fetch messages with the word "hi" in them, thus it fails
once i rewrite the way `pol count` counts stuff, it should work, but not sure if ill feel like doing that hehe :p
