### ISSUE TITLE
blacklisted roles still able to run impersonate command

### ISSUE THREAD

**Issue by jadeposting** [okbuddyhololive/polkabot#51]

**Comment by bemxio** [comment]
i looked at the code and reminded myself that it originally was supposed to work, but like in cocobot, by not allowing blacklisted roles to set a custom message
however i plan to make every command inaccessible to blacklisted roles

**Comment by bemxio** [comment]
fixed in commit [7ae887f](https://github.com/okbuddyhololive/polkabot/commit/7ae887fa440f28ad05abd08f62761cef8ca4e630)! :))
